export default {
  'courses.courses': 'Courses',
  'courses.overview': 'Courses overview',
  'course.create': 'Create a new course',
  'course.title': 'Title',
  'course.description': 'Description',
  'course.cover':'Cover',
  'course.visibility':'Select visibility option', 
  'course.start' : 'Your course starts at',
  'course.end' : 'Your course end at',
  'course.type' : 'Select type of course',
  'course.add.module': 'Add module',
  'course.lesson.new': 'Create Lesson',
  'course.curriculum': 'Curriculum',
  'course.forum': 'Forum',
  'course.courseMember': 'Course Members',
  'course.analytics': 'Analytics',
}
